const DEGREES = {
    se_ai: {
        id: 'se_ai',
        title: 'Software Engineering (AI Minor) — BE(Hons)',
        years: '2024 to 2027',
        semesters: [
            { id: 'sem-24-1', name: '2024 Sem 1', year: 2024, semNum: 1 },
            { id: 'sem-24-2', name: '2024 Sem 2', year: 2024, semNum: 2 },
            { id: 'sem-25-1', name: '2025 Sem 1', year: 2025, semNum: 1 },
            { id: 'sem-25-2', name: '2025 Sem 2', year: 2025, semNum: 2 },
            { id: 'sem-26-1', name: '2026 Sem 1', year: 2026, semNum: 1 },
            { id: 'sem-26-2', name: '2026 Sem 2', year: 2026, semNum: 2 },
            { id: 'sem-27-1', name: '2027 Sem 1', year: 2027, semNum: 1 },
            { id: 'sem-27-2', name: '2027 Sem 2', year: 2027, semNum: 2 },
        ],
        requirements: [
            { id: 'total', name: 'Total Units', target: 64, filter: () => true, color: 'var(--accent-color)' },
            { id: 'core', name: 'BE Core', target: 8, filter: c => c.cat === 'Core', color: 'var(--cat-core)' },
            { id: 'secore', name: 'SE Core', target: 34, filter: c => c.cat === 'SE Core', color: 'var(--cat-secore)' },
            { id: 'aiminor', name: 'AI Minor', target: 8, filter: c => c.cat === 'AI Minor', color: 'var(--cat-aiminor)' },
            { id: 'ext', name: 'SE Ext / Adv', target: 2, filter: c => c.cat === 'SE Ext' || c.cat === 'SE Adv', color: 'var(--cat-seext)' },
            { id: 'electives', name: 'Electives', target: 4, filter: c => c.cat === 'Elective', color: 'var(--cat-elec)' }
        ],
        courses: [
            { code: 'ENGG1100', name: 'Professional Engineering', units: 2, cat: 'Core' },
            { code: 'ENGG1001', name: 'Programming for Engineers', units: 2, cat: 'Core', exclusiveWith: ["CSSE1001"] },
            { code: 'CSSE1001', name: 'Introduction to Software Engineering', units: 2, cat: 'Core', exclusiveWith: ["ENGG1001"] },
            { code: 'MATH1051', name: 'Calculus & Linear Algebra I', units: 2, cat: 'Core', exclusiveWith: ["MATH1071"] },
            { code: 'MATH1071', name: 'Advanced Calculus & Linear Algebra I', units: 2, cat: 'Core', exclusiveWith: ["MATH1051"] },
            { code: 'MATH1052', name: 'Multivariate Calculus & Ordinary Differential Equations', units: 2, cat: 'Core', exclusiveWith: ["MATH1072"] },
            { code: 'MATH1072', name: 'Advanced Multivariate Calculus & Ordinary Differential Equations', units: 2, cat: 'Core', exclusiveWith: ["MATH1052"] },
            { code: 'SOFTWE2455', name: 'Software Engineering', units: 36, cat: 'SE Core' },
            { code: 'COMPEC2455', name: 'Computer Engineering', units: 16, cat: 'SE Core' },
            { code: 'ARINTA2455', name: 'Artificial Intelligence', units: 8, cat: 'SE Core' },
            { code: 'DATASA2455', name: 'Data Science', units: 8, cat: 'SE Core' },
            { code: 'DESGNA2455', name: 'Design', units: 8, cat: 'SE Core' },
            { code: 'DECO3800', name: 'Design Computing Studio 3 - Proposal', units: 2, cat: 'SE Ext' },
            { code: 'COMP3301', name: 'Operating Systems Architecture', units: 2, cat: 'SE Adv' },
            { code: 'COMP3320', name: 'Vulnerability Assessment and Penetration Testing', units: 2, cat: 'SE Adv' },
            { code: 'COMP3400', name: 'Functional & Logic Programming', units: 2, cat: 'SE Adv' },
            { code: 'COMP3702', name: 'Artificial Intelligence', units: 2, cat: 'AI Minor' },
            { code: 'COMP3710', name: 'Pattern Recognition and Analysis', units: 2, cat: 'AI Minor' },
            { code: 'COMP3820', name: 'Digital Health Software Project', units: 2, cat: 'SE Adv' },
            { code: 'COMP4403', name: 'Compilers and Interpreters', units: 2, cat: 'SE Adv' },
            { code: 'COMP4500', name: 'Advanced Algorithms & Data Structures', units: 2, cat: 'SE Adv' },
            { code: 'COMP4702', name: 'Machine Learning', units: 2, cat: 'AI Minor' },
            { code: 'COMP4703', name: 'Natural Language Processing', units: 2, cat: 'AI Minor' },
            { code: 'COMS3200', name: 'Computer Networks I', units: 2, cat: 'SE Adv' },
            { code: 'COMS4507', name: 'Advanced Topics in Security', units: 2, cat: 'SE Adv' },
            { code: 'COSC3000', name: 'Visualization, Computer Graphics & Data Analysis', units: 2, cat: 'SE Adv' },
            { code: 'COSC3500', name: 'High-Performance Computing', units: 2, cat: 'SE Adv' },
            { code: 'CSSE3010', name: 'Embedded Systems Design & Interfacing', units: 2, cat: 'SE Adv' },
            { code: 'CSSE3012', name: 'The Software Process', units: 2, cat: 'SE Adv' },
            { code: 'CSSE3100', name: 'Reasoning About Programs', units: 2, cat: 'SE Adv' },
            { code: 'CSSE3610', name: 'Concurrency: Theory and Practice', units: 2, cat: 'SE Adv' },
            { code: 'CSSE4010', name: 'Digital System Design', units: 2, cat: 'SE Adv' },
            { code: 'CSSE4630', name: 'Principles of Program Analysis', units: 2, cat: 'SE Adv' },
            { code: 'CYBR3000', name: 'Information Security', units: 2, cat: 'SE Adv' },
            { code: 'DECO3500', name: 'Social & Mobile Computing', units: 2, cat: 'SE Adv' },
            { code: 'INFS2200', name: 'Relational Database Systems', units: 2, cat: 'SE Adv' },
            { code: 'INFS3200', name: 'Advanced Database Systems', units: 2, cat: 'SE Adv' },
            { code: 'INFS3202', name: 'Web Information Systems', units: 2, cat: 'SE Adv' },
            { code: 'INFS3208', name: 'Cloud Computing', units: 2, cat: 'SE Adv' },
            { code: 'INFS4203', name: 'Data Mining', units: 2, cat: 'SE Adv' },
            { code: 'INFS4205', name: 'Advanced Techniques for High Dimensional Data', units: 2, cat: 'SE Adv' },
            { code: 'COMP2140', name: 'Web/Mobile Programming', units: 2, cat: 'Elective' },
            { code: 'COMP3880', name: 'International Software Development 1', units: 2, cat: 'Elective' },
            { code: 'COMP3881', name: 'International Software Development 2', units: 2, cat: 'Elective' },
            { code: 'DECO2801', name: 'Human-Centred AI', units: 2, cat: 'AI Minor' },
            { code: 'MATH2001', name: 'Calculus & Linear Algebra II', units: 2, cat: 'Elective', exclusiveWith: ["MATH2901"] },
            { code: 'MATH2901', name: 'Advanced Calculus & Linear Algebra II', units: 2, cat: 'Elective', exclusiveWith: ["MATH2001"] },
            { code: '2455', name: 'Bachelor of Engineering (Honours)', units: 64, cat: 'SE Core' },
            { code: 'COMP2701', name: 'Generative Artificial Intelligence', units: 2, cat: 'AI Minor' },
            { code: 'ELEC4630', name: 'Computer Vision and Deep Learning', units: 2, cat: 'AI Minor' },
            { code: 'STAT3006', name: 'Statistical Learning', units: 2, cat: 'AI Minor' },
            { code: 'STAT3007', name: 'Deep Learning', units: 2, cat: 'AI Minor' },
            { code: 'ELEC_GEN_1', name: 'General/BE Elective', units: 2, cat: 'Elective' },
            { code: 'ELEC_GEN_2', name: 'General/BE Elective', units: 2, cat: 'Elective' },
            { code: 'ELEC_GEN_3', name: 'General/BE Elective', units: 2, cat: 'Elective' }
        ]
    },
    cs: {
        id: 'cs',
        title: 'Computer Science (Placeholder)',
        years: '2024 to 2026',
        semesters: [
            { id: 'sem-24-1', name: '2024 Sem 1', year: 2024, semNum: 1 },
            { id: 'sem-24-2', name: '2024 Sem 2', year: 2024, semNum: 2 },
            { id: 'sem-25-1', name: '2025 Sem 1', year: 2025, semNum: 1 },
            { id: 'sem-25-2', name: '2025 Sem 2', year: 2025, semNum: 2 },
            { id: 'sem-26-1', name: '2026 Sem 1', year: 2026, semNum: 1 },
            { id: 'sem-26-2', name: '2026 Sem 2', year: 2026, semNum: 2 },
        ],
        requirements: [
            { id: 'total', name: 'Total Units', target: 48, filter: () => true, color: 'var(--accent-color)' },
            { id: 'core', name: 'CS Core', target: 16, filter: c => c.cat === 'CS Core', color: 'var(--cat-core)' },
            { id: 'electives', name: 'Electives', target: 32, filter: c => c.cat === 'Elective', color: 'var(--cat-elec)' }
        ],
        courses: [
            { code: 'COMP1100', name: 'Introduction to Software Innovation', units: 2, cat: 'CS Core' },
            { code: 'COMP2048', name: 'Theory of Computing', units: 2, cat: 'CS Core' },
            { code: 'COMP3506', name: 'Algorithms & Data Structures', units: 2, cat: 'CS Core' },
            { code: 'CSSE1001', name: 'Introduction to Software Engineering', units: 2, cat: 'CS Core', exclusiveWith: ["ENGG1001"] },
            { code: 'CSSE2002', name: 'Programming in the Large', units: 2, cat: 'CS Core' },
            { code: 'CSSE2010', name: 'Introduction to Computer Systems', units: 2, cat: 'CS Core' },
            { code: 'INFS1200', name: 'Introduction to Information Systems', units: 2, cat: 'CS Core' },
            { code: 'MATH1061', name: 'Discrete Mathematics', units: 2, cat: 'CS Core', exclusiveWith: ["MATH1081"] },
            { code: 'MATH1081', name: 'Advanced Discrete Mathematics', units: 2, cat: 'CS Core', exclusiveWith: ["MATH1061"] },
            { code: 'DECO3801', name: 'Design Computing Studio 3 - Build', units: 2, cat: 'Elective' },
            { code: 'COMP2011', name: 'Fundamentals of Data Science', units: 2, cat: 'Elective' },
            { code: 'COMP2140', name: 'Web/Mobile Programming', units: 2, cat: 'Elective' },
            { code: 'COSC2500', name: 'Numerical Methods in Computational Science', units: 2, cat: 'Elective' },
            { code: 'CSSE2310', name: 'Computer Systems Principles and Programming', units: 2, cat: 'Elective' },
            { code: 'DECO1400', name: 'Introduction to Web Design', units: 2, cat: 'Elective' },
            { code: 'DECO2500', name: 'Human-Computer Interaction', units: 2, cat: 'Elective' },
            { code: 'DECO2801', name: 'Human-Centred AI', units: 2, cat: 'Elective' },
            { code: 'INFS2200', name: 'Relational Database Systems', units: 2, cat: 'Elective' },
            { code: 'MATH1051', name: 'Calculus & Linear Algebra I', units: 2, cat: 'Elective', exclusiveWith: ["MATH1071"] },
            { code: 'MATH1071', name: 'Advanced Calculus & Linear Algebra I', units: 2, cat: 'Elective', exclusiveWith: ["MATH1051"] },
            { code: 'STAT1201', name: 'Analysis of Scientific Data', units: 2, cat: 'Elective', exclusiveWith: ["STAT1301"] },
            { code: 'STAT1301', name: 'Advanced Analysis of Scientific Data', units: 2, cat: 'Elective', exclusiveWith: ["STAT1201"] },
            { code: 'COMP3301', name: 'Operating Systems Architecture', units: 2, cat: 'Elective' },
            { code: 'COMP3320', name: 'Vulnerability Assessment and Penetration Testing', units: 2, cat: 'Elective' },
            { code: 'COMP3400', name: 'Functional & Logic Programming', units: 2, cat: 'Elective' },
            { code: 'COMP3702', name: 'Artificial Intelligence', units: 2, cat: 'Elective' },
            { code: 'COMP3710', name: 'Pattern Recognition and Analysis', units: 2, cat: 'Elective' },
            { code: 'COMP3820', name: 'Digital Health Software Project', units: 2, cat: 'Elective' },
            { code: 'COMP4403', name: 'Compilers and Interpreters', units: 2, cat: 'Elective' },
            { code: 'COMP4702', name: 'Machine Learning', units: 2, cat: 'Elective' },
            { code: 'COMP4703', name: 'Natural Language Processing', units: 2, cat: 'Elective' },
            { code: 'COMS3200', name: 'Computer Networks I', units: 2, cat: 'Elective' },
            { code: 'COSC3000', name: 'Visualization, Computer Graphics & Data Analysis', units: 2, cat: 'Elective' },
            { code: 'COSC3500', name: 'High-Performance Computing', units: 2, cat: 'Elective' },
            { code: 'CSSE3012', name: 'The Software Process', units: 2, cat: 'Elective' },
            { code: 'CSSE3100', name: 'Reasoning About Programs', units: 2, cat: 'Elective' },
            { code: 'CSSE3200', name: 'Software Engineering Studio: Design, Implement & Test', units: 2, cat: 'Elective' },
            { code: 'CYBR3000', name: 'Information Security', units: 2, cat: 'Elective' },
            { code: 'DECO3500', name: 'Social & Mobile Computing', units: 2, cat: 'Elective' },
            { code: 'INFS3200', name: 'Advanced Database Systems', units: 2, cat: 'Elective' },
            { code: 'INFS3202', name: 'Web Information Systems', units: 2, cat: 'Elective' },
            { code: 'INFS3208', name: 'Cloud Computing', units: 2, cat: 'Elective' },
            { code: 'INFS4203', name: 'Data Mining', units: 2, cat: 'Elective' },
            { code: 'INFS4205', name: 'Advanced Techniques for High Dimensional Data', units: 2, cat: 'Elective' },
            { code: 'MATH3201', name: 'Scientific Computing: Advanced Techniques & Applications', units: 2, cat: 'Elective' },
            { code: 'MATH3202', name: 'Operations Research & Mathematical Planning', units: 2, cat: 'Elective' },
            { code: 'MATH3302', name: 'Coding & Cryptography', units: 2, cat: 'Elective' },
            { code: 'CYBERC2451', name: 'Cyber Security', units: 16, cat: 'Elective' },
            { code: 'DATASC2451', name: 'Data Science', units: 16, cat: 'Elective' },
            { code: 'MACHDC2451', name: 'Machine Learning', units: 16, cat: 'Elective' },
            { code: 'PROLAC2451', name: 'Programming Languages', units: 16, cat: 'Elective' },
            { code: 'SCCOMC2451', name: 'Scientific Computing', units: 16, cat: 'Elective' },
            { code: 'DATASD2451', name: 'Data Science', units: 24, cat: 'Elective' },
            { code: 'DECO1100', name: 'Design Thinking', units: 2, cat: 'Elective' },
            { code: 'DECO1800', name: 'Design Computing Studio I - Interactive Technology', units: 2, cat: 'Elective' },
            { code: 'DECO2300', name: 'Digital Prototyping and Extended Reality', units: 2, cat: 'Elective' },
            { code: 'DECO2850', name: 'Design Computing Studio 2 - Interaction Design', units: 2, cat: 'Elective' },
            { code: 'DECO3850', name: 'Physical Computing Studio', units: 4, cat: 'Elective' },
            { code: 'ENGG1300', name: 'Introduction to Electrical Systems', units: 2, cat: 'Elective' },
            { code: 'MATH1050', name: 'Mathematical Foundations II', units: 2, cat: 'Elective' },
            { code: 'MATH1052', name: 'Multivariate Calculus & Ordinary Differential Equations', units: 2, cat: 'Elective', exclusiveWith: ["MATH1072"] },
            { code: 'MATH2001', name: 'Calculus & Linear Algebra II', units: 2, cat: 'Elective' },
            { code: 'MATH2301', name: 'Linear & Abstract Algebra & Number Theory', units: 2, cat: 'Elective' },
            { code: 'MATH2302', name: 'Discrete Mathematics II', units: 2, cat: 'Elective' },
            { code: 'MATH3104', name: 'Mathematical Biology', units: 2, cat: 'Elective' },
            { code: 'SCIE1000', name: 'Theory & Practice in Science', units: 2, cat: 'Elective' },
            { code: 'SCIE2100', name: 'Bioinformatics 1: Introduction', units: 2, cat: 'Elective' },
            { code: 'STAT2003', name: 'Mathematical Probability', units: 2, cat: 'Elective' },
            { code: 'STAT2004', name: 'Statistical Modelling & Analysis', units: 2, cat: 'Elective' },
            { code: '2451', name: 'Bachelor of Computer Science', units: 48, cat: 'Elective' },
            { code: 'CS_ELEC_1', name: 'CS Elective 1', units: 2, cat: 'Elective' },
            { code: 'CS_ELEC_2', name: 'CS Elective 2', units: 2, cat: 'Elective' }
        ]
    }
};

const CAT_COLORS = {
    'Core': 'var(--cat-core)',
    'SE Core': 'var(--cat-se)',
    'AI Minor': 'var(--cat-ai)',
    'SE Ext': 'var(--cat-ext)',
    'SE Adv': 'var(--cat-adv)',
    'CS Core': 'var(--cat-core)',
    'Elective': 'var(--cat-elec)',
};
