const DEGREES = {
    se_ai: {
        id: 'se_ai',
        title: 'Software Engineering (AI Minor) — BE(Hons)',
        years: '2024 to 2027',
        semesters: [
            { id: 'sem-24-1', name: '2024 Sem 1', year: 2024, semNum: 1 },
            { id: 'sem-24-2', name: '2024 Sem 2', year: 2024, semNum: 2 },
            { id: 'sem-25-1', name: '2025 Sem 1', year: 2025, semNum: 1 },
            { id: 'sem-25-2', name: '2025 Sem 2', year: 2025, semNum: 2 },
            { id: 'sem-26-1', name: '2026 Sem 1', year: 2026, semNum: 1 },
            { id: 'sem-26-2', name: '2026 Sem 2', year: 2026, semNum: 2 },
            { id: 'sem-27-1', name: '2027 Sem 1', year: 2027, semNum: 1 },
            { id: 'sem-27-2', name: '2027 Sem 2', year: 2027, semNum: 2 },
        ],
        requirements: [
            { id: 'total', name: 'Total Units', target: 64, filter: () => true, color: 'var(--accent-color)' },
            { id: 'core', name: 'BE Core', target: 8, filter: c => c.cat === 'Core', color: 'var(--cat-core)' },
            { id: 'secore', name: 'SE Core', target: 34, filter: c => c.cat === 'SE Core', color: 'var(--cat-secore)' },
            { id: 'aiminor', name: 'AI Minor', target: 8, filter: c => c.cat === 'AI Minor', color: 'var(--cat-aiminor)' },
            { id: 'ext', name: 'SE Ext / Adv', target: 2, filter: c => c.cat === 'SE Ext' || c.cat === 'SE Adv', color: 'var(--cat-seext)' },
            { id: 'electives', name: 'Electives', target: 4, filter: c => c.cat === 'Elective', color: 'var(--cat-elec)' }
        ],
        courses: [
            { code: 'ENGG1100', name: 'Professional Engineering', units: 2, cat: 'Core' },
            { code: 'ENGG1001', name: 'Programming for Engineers', units: 2, cat: 'Core', exclusiveWith: ["CSSE1001"] },
            { code: 'CSSE1001', name: 'Introduction to Software Engineering', units: 2, cat: 'Core', exclusiveWith: ["ENGG1001"] },
            { code: 'MATH1051', name: 'Calculus & Linear Algebra I', units: 2, cat: 'Core', exclusiveWith: ["MATH1071"] },
            { code: 'MATH1071', name: 'Advanced Calculus & Linear Algebra I', units: 2, cat: 'Core', exclusiveWith: ["MATH1051"] },
            { code: 'MATH1052', name: 'Multivariate Calculus & Ordinary Differential Equations', units: 2, cat: 'Core', exclusiveWith: ["MATH1072"] },
            { code: 'MATH1072', name: 'Advanced Multivariate Calculus & Ordinary Differential Equations', units: 2, cat: 'Core', exclusiveWith: ["MATH1052"] },
            { code: 'DECO3800', name: 'Design Computing Studio 3 - Proposal', units: 2, cat: 'SE Ext' },
            { code: 'COMP3301', name: 'Operating Systems Architecture', units: 2, cat: 'SE Adv' },
            { code: 'COMP3320', name: 'Vulnerability Assessment and Penetration Testing', units: 2, cat: 'SE Adv', prereqs: ["CYBR3000"] },
            { code: 'COMP3400', name: 'Functional & Logic Programming', units: 2, cat: 'SE Adv' },
            { code: 'COMP3702', name: 'Artificial Intelligence', units: 2, cat: 'AI Minor', prereqs: ["CSSE1001","ENGG1001"] },
            { code: 'COMP3710', name: 'Pattern Recognition and Analysis', units: 2, cat: 'AI Minor', prereqs: ["MATH1051","MATH1071","CSSE1001","ENGG1001"] },
            { code: 'COMP3820', name: 'Digital Health Software Project', units: 2, cat: 'SE Adv', prereqs: ["COMP2140"] },
            { code: 'COMP4403', name: 'Compilers and Interpreters', units: 2, cat: 'SE Adv' },
            { code: 'COMP4500', name: 'Advanced Algorithms & Data Structures', units: 2, cat: 'SE Adv' },
            { code: 'COMP4702', name: 'Machine Learning', units: 2, cat: 'AI Minor', prereqs: ["CSSE1001","ENGG1001","MATH1051","MATH1071"] },
            { code: 'COMP4703', name: 'Natural Language Processing', units: 2, cat: 'AI Minor', prereqs: ["CSSE1001","ENGG1001"] },
            { code: 'COMS3200', name: 'Computer Networks I', units: 2, cat: 'SE Adv' },
            { code: 'COMS4507', name: 'Advanced Topics in Security', units: 2, cat: 'SE Adv', prereqs: ["CYBR3000"] },
            { code: 'COSC3000', name: 'Visualization, Computer Graphics & Data Analysis', units: 2, cat: 'SE Adv' },
            { code: 'COSC3500', name: 'High-Performance Computing', units: 2, cat: 'SE Adv' },
            { code: 'CSSE3010', name: 'Embedded Systems Design & Interfacing', units: 2, cat: 'SE Adv' },
            { code: 'CSSE3012', name: 'The Software Process', units: 2, cat: 'SE Adv', prereqs: ["COMP2140"] },
            { code: 'CSSE3100', name: 'Reasoning About Programs', units: 2, cat: 'SE Adv' },
            { code: 'CSSE3610', name: 'Concurrency: Theory and Practice', units: 2, cat: 'SE Adv' },
            { code: 'CSSE4010', name: 'Digital System Design', units: 2, cat: 'SE Adv' },
            { code: 'CSSE4630', name: 'Principles of Program Analysis', units: 2, cat: 'SE Adv', prereqs: ["COMP4403"] },
            { code: 'CYBR3000', name: 'Information Security', units: 2, cat: 'SE Adv' },
            { code: 'DECO3500', name: 'Social & Mobile Computing', units: 2, cat: 'SE Adv', prereqs: ["CSSE1001","ENGG1001"] },
            { code: 'INFS2200', name: 'Relational Database Systems', units: 2, cat: 'SE Adv' },
            { code: 'INFS3200', name: 'Advanced Database Systems', units: 2, cat: 'SE Adv', prereqs: ["INFS2200"] },
            { code: 'INFS3202', name: 'Web Information Systems', units: 2, cat: 'SE Adv', prereqs: ["CSSE1001","ENGG1001"] },
            { code: 'INFS3208', name: 'Cloud Computing', units: 2, cat: 'SE Adv', prereqs: ["CSSE1001"] },
            { code: 'INFS4203', name: 'Data Mining', units: 2, cat: 'SE Adv', prereqs: ["CSSE1001","ENGG1001","INFS2200"] },
            { code: 'INFS4205', name: 'Advanced Techniques for High Dimensional Data', units: 2, cat: 'SE Adv', prereqs: ["INFS2200"] },
            { code: 'COMP2140', name: 'Web/Mobile Programming', units: 2, cat: 'Elective', prereqs: ["CSSE1001","ENGG1001"] },
            { code: 'COMP3880', name: 'International Software Development 1', units: 2, cat: 'Elective', prereqs: ["CSSE1001","ENGG1001"] },
            { code: 'COMP3881', name: 'International Software Development 2', units: 2, cat: 'Elective', prereqs: ["CSSE1001","ENGG1001"] },
            { code: 'DECO2801', name: 'Human-Centred AI', units: 2, cat: 'AI Minor', prereqs: ["CSSE1001","ENGG1001"] },
            { code: 'MATH2001', name: 'Calculus & Linear Algebra II', units: 2, cat: 'Elective', exclusiveWith: ["MATH2901"], prereqs: ["MATH1051","MATH1071","MATH1052","MATH1072"] },
            { code: 'MATH2901', name: 'Advanced Calculus & Linear Algebra II', units: 2, cat: 'Elective', exclusiveWith: ["MATH2001"], prereqs: ["MATH1051","MATH1071","MATH1052","MATH1072"] },
            { code: 'COMP2701', name: 'Generative Artificial Intelligence', units: 2, cat: 'AI Minor', prereqs: ["CSSE1001","ENGG1001"] },
            { code: 'ELEC4630', name: 'Computer Vision and Deep Learning', units: 2, cat: 'AI Minor' },
            { code: 'STAT3006', name: 'Statistical Learning', units: 2, cat: 'AI Minor', prereqs: ["MATH1051","MATH1071","MATH1052","MATH1072","CSSE1001","ENGG1001"] },
            { code: 'STAT3007', name: 'Deep Learning', units: 2, cat: 'AI Minor' },
            { code: 'ELEC_GEN_1', name: 'General/BE Elective', units: 2, cat: 'Elective' },
            { code: 'ELEC_GEN_2', name: 'General/BE Elective', units: 2, cat: 'Elective' },
            { code: 'ELEC_GEN_3', name: 'General/BE Elective', units: 2, cat: 'Elective' }
        ]
    }
};

const CAT_COLORS = {
    'Core': 'var(--cat-core)',
    'SE Core': 'var(--cat-se)',
    'AI Minor': 'var(--cat-ai)',
    'SE Ext': 'var(--cat-ext)',
    'SE Adv': 'var(--cat-adv)',
    'Elective': 'var(--cat-elec)',
};
